sudo: required
dist: trusty
language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script: yarn add polymer-cli
script:
  - xvfb-run wct --module-resolution=node --npm --skip-plugin sauce
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --module-resolution=node --npm --plugin sauce --skip-plugin local; fi'
after_success:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET" -in deploy.enc -out deploy_key -d; fi'
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 755 ghp.sh
  - ./ghp.sh
env:
  global:
    - secure: AbmMfu75p+buVQxUFuhWecGlhTKnlwIybDtxIIlRZbbN9nkieSmZuPNdz7FRG2WvSjsfCfDBvJFIN7iPtxXhpCftXGNZnvf/4Ng9/HkBXuoQ2olfG6M9NPP2PF6EIZdBaBfx+jDwCrgVdi1NHlP/02su/OJY8rWYJORanZ/C0mjWdqWkTQjkp8W/G1G54lFSN1zUDFUmTSN+F+9FASf8KsXO9eVf7v2V0An9L/V+TjuyfBiEMlm6/9g+Z1iB2ha9P65owCIHbhDhmABGRxPadnwKQcfSt+QFlgUBhX3SNFuag1SsC4+ML1lLP8ra0B8tP84ef4VmjnS+KTUGHhkDk1MT31NWVjaLsdielSGFT343MOp+edZwM3Azfiv/7gBq2DsCi1UCPPxKySJ9UNMcrIGeLVFuzIXru/01/A504YVBkXY7hWByWA0Yqej4jwlAMEhyusuZq6KfZQbArpa6c6DHERjbVK6dU/NVl8945uTGUwuhQn0D871ZysXgzb5WGRFsXQM77MF7dm0CSSWM9TpA/VUrmerxMCMGi1c5v7OUhJ21eIrtoEQ2ifR0gKgKOf0O7DsVI2Uf7c++YCgFofWg/PVH9+kMUwTXKKo48yp3VtTBCVvoyKCl4Q4SAbHmYGUBOggx1/ZuNMAGRS1jSEMdF29FoiIzKYtlyLAqPRM=
    - secure: DG6bJLAvSb2vD8+gbcrgUkCkd0bm/+4PA5hNND7YzbWZVm9vv0idMzi7ANXB408Yw8AfjWcvO2RghiUiADLvvx7f9fY5qtKP6zF3JdKlO3rg6F0CkgMsSEtYHozEYA/fRJKhKBHKvY9wiKhK9wwhDk23Hwkju+VnzLDH2gp95j9JbgZNl/eTsIGPo4m/qLqoKAfcYD5Nos3SpEc4UKj22OV2lyGQEFuewqFUpWosOz0slKxbdx6NwsIZIDyyKfOBTMIDnVWJ00YSfHhgbE+jZTxTHV5eCpldL+PwQB4cX04oM/SqRkBSr2MOfrtbvufOL4K3OZSXRzg8skuXJNtBgqZXxSM24c37mTRE68GPrnhY8ujrJE4LQrt4DjIUzGYKusBhSQqgJsBQNucAEVx6ISS3E2VPXA/FcfeLAs1MpXtCLrs1kWJ83UY0M9MDeOx/r1ogvbuuGTzYqWKnSZObjLLgVUMiyslfM7O7wE6oX6cpbEgqBg5DueOWyu1RECKASP76p/ohTcZysvxAplnUePs/a+RHX2np32RVRoXhYl1Fy1BMPCqFykMsihKaPSs4NjDZ2ZSDClOAB/fhNvHpBF/aPo7C3QoQbJs+AqC9xu4wAuIcljrkP2L/ETHAEFiiOEXjnvBHKvwm7MWn82JdhZf3Io5x63ue6PrweQwhu2o=
    - secure: eY1hC8ES8IeoFUoO5slZmmG3kOEcnCpspruG3+qAHyDCkszYdVmknQK7uTsOpI6zTYI1zJogvJ/xhRJdbbE8v8xcTFDN/B0MPdfLlI7EaN/xa48dBz8jJqBQKXe9DrYLDClruUXMzB4r5/ZITEypArKZlPNCAoiQLIJH4Gnm9iK9AuJK6ri8nsBsikOl8Y1zXEyXlJkqZcPUJ4eIV0HMqATJhaSts1JnS/rt8QVuP1wygMh3FeHHxIV67F3Ll5mkkeV2p1MjoKJWwwGJ9T3yWC841tS+rCQQkT10NpB1ODtzIFGBc96ETmW8aS9F9+mI1BiLNOkQCnKnmdMirOsDVksOC9lhAxJ57y+V91wcKHOb2q1w1IjOptC1qBvsxPnC8uRii3z9lvqI8B/1a0wzul2dkU4aceWn6bD3JcZD3RGCb1fKzbKHAk4MguykYo4//wMjA9CO1dn8Bzk7v76CcHJAyWB4MWPiNHWVCzigt2mzuLoTljvRKuyufBwfYSymt59Lxxr8kSQyoVQSniqEkeajNgd50qy9GXVQhSE+CyhHflNp/7HGIxgpDBa+20+WGIbJPNCEFFDf+7XyiLKytp+2iU0GMBIPbDw5n4RI/UcxwPK4vvcuSh563PTxrWVixesZ5P7FOax4zmBkE8CaT9Awxf14YPc7rw6tBW75QjA=
    - secure: WGwNHPopPoU5NGhF05TrWoXd0MdjAVbQT0vE8N/Jx1ASWIj5Z7/g2PWkdjeyHj9RzZo3AJKL0t91J34LQ050HTrUZ6Xis5UfbJ/rUkemCAWhGwrpCPvl1LBcpZ61au3fOTqEzDZi1fmrbAXdsAjPUOLUJb8WWQ0bX9aN1hw21xWKMZLT3gsaVpuGPW6CUQeue+8otTiIuXSovRdS8hwURX/bNABisIy0yF3ccD1RFoaTBNuxLQNzMSR2VS+xOUIQLwC7UWiWTMACxdaG10n+ZpwLcclcawg7zrgqBovWdui3dG9F7odXoipwSModShgRCdMqWOVtrukUEiC0M/PArwKiXkhn8FQ7ZehwMlkgLuvawcXNIpiB7fUTqNC9UtTgfcBJupFbIw5Qr96SjyHFYR0bOLnjKVQiQRe8fpdZIVjzkayWK0F0xasjYJyCPa8NnLGVneogEGpjaTEJdqRqUB1HWFzvPJ2GNoQ2G99zcyCFdJbfpn3P1lz2HhMLvlUmojl8gi/hp64b2tNX9LJz/sRglFFpg7LHoh2//XOFieHQVJ+sDImpXRoZ5x91jT8w8gYIP8Tfc0hhChQ5EbSEbPw8fwCGIVs5AtAW00g5/Zz4JGgImBTNgGwz7uVfZm9SdnjMw/oGkSKwD1NODZSvvtx0iGtMxF+X5pSAzLuSl4E=

